### ISSUE TITLE
Can't configure the plugin

### ISSUE THREAD

**Issue by llune** [OblikStudio/kirby-git#4]
Hi!

I've tried installing the plugin manually because I'm not sure I can use composer on my shared web hosting service. There is git though (2.24.1).

I've set my config file like this:

```
    'oblik.git.repo' => 'path-repository',
    'oblik.git.merge' => 'master',
    'oblik.git.hooks' => [
        'site.update:after',
        'page.update:after'
    ],
```

<img width="381" alt="Capture d’écran 2020-06-06 à 16 09 33" src="https://user-images.githubusercontent.com/6073336/83946363-8efb5300-a810-11ea-8358-1e9091f6889d.png">

I don't really understand the mistake here. Could you help me understand what's wrong?

**Comment by hdodov** [comment]
I need to work on more user-friendly error messages... the "Unknown option" thing means the plugin tries to use a command that Git doesn't understand, which in turn means that the Git version on your server is too old. You can check it by running `git --version`.

In [the readme](https://github.com/OblikStudio/kirby-git#installation), you can see the minimum required Git version, which is `2.22.0`. Upgrade it and let me know if you have further problems. 👍

**Comment by llune** [comment]
The Git version on the server is 2.24.1. Is it not correct?

**Comment by hdodov** [comment]
Hm, then perhaps there are multiple versions of Git on your server. It's possible that the one you use when you run `git --version` is separate from the one that the PHP scripts use. To check that, create a sample PHP script like this:

```php
echo exec('git --version');
```

...and see what this outputs.

---

You can also enable [the log file option](https://github.com/OblikStudio/kirby-git#log) of the plugin so that each executed command is logged, and paste the results here. That can help us resolve the issue in case a command is malformed.

**Comment by hdodov** [comment]
@llune have you solved the issue?
